In [1]:
print("Hola PARAMANGLA")

Hola PARAMANGLA

# Semana 1 · Día 3: mi primer notebook
Análisis de humedad de 5 lotes de cacao de PARAMANGLA. Requisito: humedad máxima 2 %.

In [2]:
humedad = [1.6, 2.8, 1.9, 2.1, 1.7]

promedio = sum(humedad) / len(humedad)
print("Promedio:", round(promedio, 2))
print("Máximo:", max(humedad))
print("Mínimo:", min(humedad))

Promedio: 2.02
Máximo: 2.8
Mínimo: 1.6

In [3]:
fuera = 0
for h in humedad:
    if h > 2:
        fuera = fuera + 1

print("Lotes fuera de requisito:", fuera, "de", len(humedad))
print("Porcentaje fuera:", round(fuera / len(humedad) * 100, 1), "%")

Lotes fuera de requisito: 2 de 5
Porcentaje fuera: 40.0 %

In [4]:
humedad = [1.0, 1.2, 1.3, 1.5, 2.9]

promedio = sum(humedad) / len(humedad)
print("Promedio:", round(promedio, 2))
print("Máximo:", max(humedad))
print("Mínimo:", min(humedad))

Promedio: 1.58
Máximo: 2.9
Mínimo: 1.0

In [5]:
fuera = 0
for h in humedad:
    if h > 2:
        fuera = fuera + 1

print("Lotes fuera de requisito:", fuera, "de", len(humedad))
print("Porcentaje fuera:", round(fuera / len(humedad) * 100, 1), "%")

Lotes fuera de requisito: 1 de 5
Porcentaje fuera: 20.0 %

In [6]:
import pandas as pd
df=pd.read_csv("../data/raw/lotes_humedad.csv")
df

   lote       fecha proveedor  humedad
0  L001  2026-10-01       P01      1.6
1  L002  2026-10-01       P02      2.8
2  L003  2026-10-02       P01      1.9
3  L004  2026-10-02       P03      2.1
4  L005  2026-10-03       P02      1.7

In [7]:
print("Promedio: ", round(df['humedad'].mean(), 2))
print("Lotes fuera de requisito:", (df['humedad'] > 2).sum())

df[df['humedad'] > 2]

Promedio:  2.02
Lotes fuera de requisito: 2

   lote       fecha proveedor  humedad
1  L002  2026-10-01       P02      2.8
3  L004  2026-10-02       P03      2.1